### PR TITLE
🔥 Removed unnecessary ternary

### PR DESCRIPTION
**Pull request by KevinGhadyani-Okta**
I removed an unnecessary ternary from `TextInput`.

### CODE REVIEW

**Review by arnoldsandoval-okta — APPROVED** [review]
Thanks!

**Review by jeffbelser-okta — CHANGES_REQUESTED** [review]
lets change the [commit format to match our standard](https://github.com/okta/odyssey/blob/develop/README.md#making-a-commit) then we can merge.

**Comment by KevinGhadyani-Okta** [comment]
Ah, I see. I'm familiar with Conventional Commits and made my own implementation, but the ones I saw on `npm` cared about how we write our individual commit titles.

I updated the PR title, but I'm wondering if you want me to change the commit titles too.

I made this change on GitHub.com, so I might need to pull down this branch and force-push an interactive rebase to fix commit titles.

**Comment by jeffbelser-okta** [comment]
@KevinGhadyani-Okta thanks, the problem here is the commit title, it needs to be reworked to match our convention. Updating the PR title won't be enough

**Comment by jeffbelser-okta** [comment]
@KevinGhadyani-Okta[ you'll want to use the correct commit type here, `chore` or `refactor` is fine.](https://www.conventionalcommits.org/en/v1.0.0/#summary)

**Comment by KevinGhadyani-Okta** [comment]
You're right, this isn't a `fix` commit. My bad.

**Review by jeffbelser-okta — APPROVED** [review]
strong work 💪

**Pull request merged**
