### PR TITLE
fix(odyssey-react): multiselect height no longer changes on selection

### PR DESCRIPTION
**Pull request by edburyenegren-okta**
### Description

Updates height calculations for MultiSelect to ensure height doesn't change when options are selected.

This PR also adds Tokens in place of Sass variables where code was refactored.

msheight

### CODE REVIEW

**Comment by KevinGhadyani-Okta** [comment]
What does this look like with multiple items selected?

**Comment by edburyenegren-okta** [comment]
We still extend the Input downward, rather than introduce a scroll or overflow:

Screen Shot 2022-05-18 at 1 22 49 PM

This change should only affect single-line height calculation.

**Comment by edburyenegren-okta** [comment]
@odyssey-eng-okta re: both Sass var questions, I actually added [this ticket](https://oktainc.atlassian.net/browse/OKTA-499834) for next sprint to remove all sass vars 😅 

We don't utilize Sass output from StyleDict, so our Sass vars and CSS vars have different SOTs right now. We haven't updated any of the sass vars since `0.7.0`, and there's already been some drift.

I don't like the all-css-values-as-public-api setup either, but it's become our standard approach 😞

**Comment by odyssey-eng-okta** [comment]
@edburyenegren-okta makes sense thank you

**Pull request merged**
