### PR TITLE
Docs: SVG optimization

### PR DESCRIPTION
**Pull request by edburyenegren-okta**
- optimizes all SVG illustrations (same config as icons, except no classes were added and colors were not replaced)
- updates DocsCard css for new SVGs (sets a max-width for coin images)

### CODE REVIEW

**Review by arnoldsandoval-okta — APPROVED** [review]
LGTM

**Comment by edburyenegren-okta** [comment]
@arnoldsandoval-okta can I get a re-review? I had to add a shrinkwrap class onto the required `div` to ensure these scale nicely cross-browser.

**Comment by edburyenegren-okta** [comment]
@jmelberg-okta this is mainly an SVG optimization branch with some Vue and CSS changes to accommodate feedback from design. 

Relevant component changes are here:

- https://github.com/okta/odyssey/pull/807/files#diff-a8b7555596b81189910266dfc42d070e48b00066f5cbe165934f41b37ca9ebb6
- https://github.com/okta/odyssey/pull/807/files#diff-08388bd9ad955afbe1eeec93105fdd739a66bfbde4a4427e8d6777342a1bcadd
- https://github.com/okta/odyssey/pull/807/files#diff-f92fa8763ccb63d14ca79f12cfbf43fa000333c45fae2a22cc273e2fdaeaf802

**Comment by edburyenegren-okta** [comment]
@arnoldsandoval-okta - could you re-review? just force-pushed to fix that conflict

**Comment by jmelberg-okta** [comment]
@edburyenegren-okta - Can you expand on what "SVG optimization" entails am curious if this is something we'll need to do regularly.

**Review by jmelberg-okta — APPROVED** [review]

**Comment by edburyenegren-okta** [comment]
@jmelberg-okta For now, manually running docs SVG assets against our [Icon package SVGO config](https://github.com/okta/odyssey/blob/master/packages/odyssey-icons/.svgo.yml). For the most part it removes extraneous attrs and dom elements. In this case no classes are added, and colors are not replaced.

@arnoldsandoval-okta and I have plans to handle this via webpack in the near future, but it was out of scope for this release.

noted on the other PR - i'll be re-running SVGO against the updated assets in here. I can ping you after that happens if you'd like to re-review. shouldn't be any changes other than the automated output.

**Comment by jmelberg-okta** [comment]
Thanks @edburyenegren-okta - sounds like a great opportunity to share some logic across Odyssey packages!

**Comment by arnoldsandoval-okta** [comment]
LGTM x2

**Pull request merged**
