### PR TITLE
fix: specfy accessibility tags section508, wcag21aa

### PR DESCRIPTION
**Pull request by ganeshsomasundaram-okta**
### Description

fix: specfy accessibility tags section508, wcag21aa

### CODE REVIEW

**Review by edburyenegren-okta — APPROVED** [review]

**Comment by edburyenegren-okta** [comment]
`wcag22aa` and `best-practices` would be great adds if they don't introduce a ton of new errors/constraints.

**Comment by KevinGhadyani-Okta** [comment]
I also recommend adding `wcag22aa` and `best-practices`.

**Review by KevinGhadyani-Okta — APPROVED** [review]
Approved, but I'd also like to look into adding those other validations as well like **Shred** suggested.

**Comment by ganeshsomasundaram-okta** [comment]
> `wcag22aa` and `best-practices` would be great adds if they don't introduce a ton of new errors/constraints.

I have added `wcag22aa`. I'm running into some a11y issues when adding `best-practice` that is related to how storybook is generated (specifically iframes and such). We can add this later once we figure out how to exclude these errors. I would like to focus on adding more tests to covers all components/interactions.

**Comment by KevinGhadyani-Okta** [comment]
Let's get a ticket for ignoring errors and getting this updated with `best-practices`, then it's safe to merge.

**Comment by ganeshsomasundaram-okta** [comment]
> Let's get a ticket for ignoring errors and getting this updated with `best-practices`, then it's safe to merge.

https://oktainc.atlassian.net/browse/OKTA-620542

**Pull request merged**
